/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaViajes.presentacion;

import agenciaViajes.negocio.GestorClientes;
import javax.swing.JInternalFrame;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author ahurtado
 */
public class ContadorClientes extends javax.swing.JFrame implements AView{

    /**
     * Creates new form ContadorClientes
     */
    
    private GestorClientes clientes;
    public ContadorClientes(GestorClientes clientes) {
        initComponents();
        this.clientes=clientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Numero de Clientes Seleccionados");
        getContentPane().add(jLabel1);

        jLabel2.setText("0");
        getContentPane().add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel aModel) {
        jLabel2.setText(""+clientes.size());
        System.out.println(""+clientes.size());
       
    }
}
